# Generated by Django 2.1.7 on 2019-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('grow_time', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
            ],
        ),
    ]
